### ISSUE TITLE
Not working for my video clips

### ISSUE THREAD

**Issue by pp3993** [cyberj0g/holo-detector#1]
Hi cvberj0g,
I tried your method for my dataset (dataset is credit card), where i recorded the 10 sec video of my data, but its not giving any label mark on the hologram used. 
Do i need to change the dimension in the code?
please reply!

**Comment by pp3993** [comment]
I have shared my video file, Even its not working for this also
Thanks

**Comment by pp3993** [comment]
[VID_20190529_154141.zip](https://github.com/cyberj0g/holo-detector/files/3231973/VID_20190529_154141.zip)

**Comment by chai-ks** [comment]
Hello Ivan,
 I was working on this project. However I am receiving the following error. Could you please take a look at this? Any help would be highly appreciated.
Thank you

OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Traceback (most recent call last):
  File "detect_holo.py", line 57, in <module>
    main()
  File "detect_holo.py", line 45, in main
    holo_mask, img_holo = detector.detect_holos(frame, False)
  File "/home/margarita/Documents/machine learning/holo-detector-master/holo_detector.py", line 174, in detect_holos
    self.holo_stack[..., self.cur_stack_idx] = cv2.resize(unwarped_hsv, self.holo_res, cv2.INTER_CUBIC)
TypeError: Expected Ptr<cv::UMat> for argument '%s'

**Comment by Cly1st** [comment]
> Hello Ivan, I was working on this project. However I am receiving the following error. Could you please take a look at this? Any help would be highly appreciated. Thank you
> 
> OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)' OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v' Traceback (most recent call last): File "detect_holo.py", line 57, in main() File "detect_holo.py", line 45, in main holo_mask, img_holo = detector.detect_holos(frame, False) File "/home/margarita/Documents/machine learning/holo-detector-master/holo_detector.py", line 174, in detect_holos self.holo_stack[..., self.cur_stack_idx] = cv2.resize(unwarped_hsv, self.holo_res, cv2.INTER_CUBIC) TypeError: Expected Ptrcv::UMat for argument '%s'

This could be a bit late.
However, for anyone who's face the same issue as this; please change the code on line 34 from `cv2.VideoWriter_fourcc(*'XVID')` to `cv2.VideoWriter_fourcc('m', 'p', '4', 'v')`.
